pipeline:
  name: webapp
  identifier: webapp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: harnessgitconnector
        build: <+input>
  stages:
    - stage:
        name: docker build
        identifier: docker_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessk8sconnector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: github
                    build:
                      type: branch
                      spec:
                        branch: master
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: docker
                    image: python:3.14
                    shell: Bash
                    command: |-
                      pip install --upgrade pip 
                      pip3 install flask
                      flask --app main.py run --host "0.0.0.0"
                  timeout: 1m
